/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MafiaIndexRouteImport } from './routes/mafia/index'
import { Route as PrototypeMafiaRouteImport } from './routes/prototype.mafia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MafiaIndexRoute = MafiaIndexRouteImport.update({
  id: '/mafia/',
  path: '/mafia/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMafiaRoute = PrototypeMafiaRouteImport.update({
  id: '/prototype/mafia',
  path: '/prototype/mafia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
  '/mafia/': typeof MafiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
  '/mafia': typeof MafiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
  '/mafia/': typeof MafiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prototype/mafia' | '/mafia/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prototype/mafia' | '/mafia'
  id: '__root__' | '/' | '/prototype/mafia' | '/mafia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototypeMafiaRoute: typeof PrototypeMafiaRoute
  MafiaIndexRoute: typeof MafiaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mafia/': {
      id: '/mafia/'
      path: '/mafia'
      fullPath: '/mafia/'
      preLoaderRoute: typeof MafiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/mafia': {
      id: '/prototype/mafia'
      path: '/prototype/mafia'
      fullPath: '/prototype/mafia'
      preLoaderRoute: typeof PrototypeMafiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeMafiaRoute: PrototypeMafiaRoute,
  MafiaIndexRoute: MafiaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
