/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MafiaRouteImport } from './routes/mafia'
import { Route as PrototypeMafiaRouteImport } from './routes/prototype.mafia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MafiaRoute = MafiaRouteImport.update({
  id: '/mafia',
  path: '/mafia',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMafiaRoute = PrototypeMafiaRouteImport.update({
  id: '/prototype/mafia',
  path: '/prototype/mafia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mafia': typeof MafiaRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mafia': typeof MafiaRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mafia': typeof MafiaRoute
  '/prototype/mafia': typeof PrototypeMafiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mafia' | '/prototype/mafia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mafia' | '/prototype/mafia'
  id: '__root__' | '/' | '/mafia' | '/prototype/mafia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MafiaRoute: typeof MafiaRoute
  PrototypeMafiaRoute: typeof PrototypeMafiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mafia': {
      id: '/mafia'
      path: '/mafia'
      fullPath: '/mafia'
      preLoaderRoute: typeof MafiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/mafia': {
      id: '/prototype/mafia'
      path: '/prototype/mafia'
      fullPath: '/prototype/mafia'
      preLoaderRoute: typeof PrototypeMafiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MafiaRoute: MafiaRoute,
  PrototypeMafiaRoute: PrototypeMafiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
