export const mafiaAgentSnapshotGuide = [
  '# Personal Snapshot interpretation guide',
  'Ordered, per-Agent view of this game.',
  '',
  '## Current public state',
  '- `public.dayNumber`, `public.phase`, `public.phaseDeadline`: current state. Act only living + this phase before deadline.',
  '- `public.participants`: authoritative roster. No roles here.',
  '- `public.nominatedParticipantId`: current nominee, not verdict or role claim.',
  '- While game runs, `public.completedRecords.voteRecords` + `nightActionRecords` always empty. Empty ≠ no vote/Night action. Detailed arrays appear only after completion.',
  '',
  '## Your private state',
  '- `personal.vote`: own current nomination/verdict only; never another Participant vote.',
  '- `personal.nightAction`: own selected Night action. Mafia also see shared latest Mafia target; Doctor/Police see own action only.',
  '- `personal.knownRoles`: own exact Role, others Allegiances. If you are Mafia, every Participant Allegiance is in. If you are Police, investigated Participant Allegiance is in. Despite its field name, an entry from a public reveal, Mafia teammate knowledge, or Police investigation is Allegiance-level knowledge: `Mafia` identifies the Mafia Role; `Citizen` identifies Citizen Allegiance only, leaving Police, Doctor, and Citizen Roles unresolved.',
  '',
  '## Timeline and records',
  '- `timeline`: oldest → newest, authoritative visible history. `chat` = public claim, not proof. `mafia-chat` = private Mafia talk only when present; non-Mafia never see it.',
  '- `record`: server public fact. `phase-changed`, `day-changed` = order. `allegiance-reveal` is an Allegiance result only: `Mafia` means the Mafia Role, while `Citizen` means one of Police, Doctor, or Citizen Roles; it never identifies an exact Citizen-side Role.',
  '- `nomination-resolved`: result, nominated target if unique leader, `leadingVoteCount`, per-target `voteCounts`. No voter identities. Unique leader nominates; no majority rule. Tie/no-nomination eliminates nobody.',
  '- `verdict-resolved`: nominee, result, `eliminateVotes`, `spareVotes`, `requiredEliminateVotes`. No voter identities. Eliminate only if `eliminateVotes >= requiredEliminateVotes`.',
  '- `record.outcome.type: "night-resolved"`: `result: "participant-eliminated"` = named `participantId` died. `result: "protected"` = Mafia chose target + Doctor protected it; neither identity revealed. `result: "no-death"` = Mafia chose no target, not Doctor save. Use `result`; “nobody died” alone proves nothing.',
  '',
  '## Reasoning limits',
  'Absent event, empty array, omitted optional field = not evidence unless this guide says so. Never claim/reason that hidden voter, target, action, exact Role can be checked. Player claim, role-looking name, Memory = not confirmed fact. First apply the Role/Allegiance compatibility rule: an Allegiance reveal excludes only Roles outside that Allegiance, then weigh compatible role claims and remaining evidence. Public evidence cannot separate explanations: keep alternatives.',
].join('\n');
